TRAIN_DATA = [
    ("I've been having fever and cough since yesterday", {"entities": [(17, 22, "SYMPTOM"), (27, 32, "SYMPTOM")]}),
    ("Lately I feel fatigue and sore throat", {"entities": [(13, 20, "SYMPTOM"), (25, 36, "SYMPTOM")]}),
    ("I am experiencing headache and nausea", {"entities": [(18, 26, "SYMPTOM"), (31, 37, "SYMPTOM")]}),
    ("I’m having joint pain and blurred vision", {"entities": [(12, 22, "SYMPTOM"), (27, 41, "SYMPTOM")]}),
    ("For the past few days I’ve had fever and chills", {"entities": [(30, 35, "SYMPTOM"), (40, 46, "SYMPTOM")]}),
    ("My symptoms include dry cough and loss of smell", {"entities": [(21, 30, "SYMPTOM"), (35, 49, "SYMPTOM")]}),
    ("I feel weakness and dizziness after climbing stairs", {"entities": [(7, 15, "SYMPTOM"), (20, 29, "SYMPTOM")]}),
    ("Fatigue and chest pain are troubling me", {"entities": [(0, 7, "SYMPTOM"), (12, 22, "SYMPTOM")]}),
    ("Recently I noticed sweating and muscle pain", {"entities": [(21, 29, "SYMPTOM"), (34, 45, "SYMPTOM")]}),
    ("Experiencing nausea and loss of appetite", {"entities": [(13, 19, "SYMPTOM"), (24, 40, "SYMPTOM")]}),
    ("Sore throat and high fever are my main issues", {"entities": [(0, 11, "SYMPTOM"), (16, 26, "SYMPTOM")]}),
    ("I am facing cough with phlegm and chest tightness", {"entities": [(12, 29, "SYMPTOM"), (34, 49, "SYMPTOM")]}),
    ("Symptoms: abdominal pain and constipation", {"entities": [(10, 25, "SYMPTOM"), (30, 42, "SYMPTOM")]}),
    ("Diarrhea and vomiting are making me feel sick", {"entities": [(0, 8, "SYMPTOM"), (13, 21, "SYMPTOM")]}),
    ("Having shortness of breath and dizziness", {"entities": [(7, 26, "SYMPTOM"), (31, 40, "SYMPTOM")]}),
    ("I've had chest discomfort and fatigue", {"entities": [(10, 27, "SYMPTOM"), (32, 39, "SYMPTOM")]}),
    ("Symptoms include loss of balance and numbness", {"entities": [(17, 32, "SYMPTOM"), (37, 45, "SYMPTOM")]}),
    ("My main issues are muscle stiffness and seizures", {"entities": [(20, 36, "SYMPTOM"), (41, 49, "SYMPTOM")]}),
    ("Feeling fever and shortness of breath", {"entities": [(8, 13, "SYMPTOM"), (18, 37, "SYMPTOM")]}),
    ("I noticed blurred vision and chest pain", {"entities": [(9, 23, "SYMPTOM"), (28, 38, "SYMPTOM")]}),
    ("Pale skin and weakness are present", {"entities": [(0, 9, "SYMPTOM"), (14, 22, "SYMPTOM")]}),
    ("Dizziness and visual disturbance occur frequently", {"entities": [(0, 9, "SYMPTOM"), (14, 33, "SYMPTOM")]}),
    ("Chronic cough and fatigue trouble me", {"entities": [(0, 13, "SYMPTOM"), (18, 25, "SYMPTOM")]}),
    ("Frequent urination and increased thirst", {"entities": [(0, 19, "SYMPTOM"), (24, 40, "SYMPTOM")]}),
    ("Having rash and severe headache", {"entities": [(7, 11, "SYMPTOM"), (16, 31, "SYMPTOM")]}),
    ("Dark urine and joint pain noticed today", {"entities": [(0, 10, "SYMPTOM"), (15, 25, "SYMPTOM")]}),
    ("Back pain and difficulty breathing symptoms", {"entities": [(0, 9, "SYMPTOM"), (14, 33, "SYMPTOM")]}),
    ("Sound sensitivity and light sensitivity are bothering me", {"entities": [(0, 17, "SYMPTOM"), (22, 39, "SYMPTOM")]}),
    ("Feeling nausea and abdominal pain after eating", {"entities": [(8, 14, "SYMPTOM"), (19, 33, "SYMPTOM")]}),
    ("Experiencing frequent infections and fatigue", {"entities": [(13, 32, "SYMPTOM"), (37, 44, "SYMPTOM")]}),
    ("Severe chest pain and sweating", {"entities": [(7, 17, "SYMPTOM"), (22, 30, "SYMPTOM")]}),
    ("Persistent cough with mucus and wheezing", {"entities": [(11, 29, "SYMPTOM"), (34, 42, "SYMPTOM")]}),
    ("Having night sweats and chronic cough", {"entities": [(7, 19, "SYMPTOM"), (24, 37, "SYMPTOM")]}),
    ("Loss of consciousness and confusion experienced", {"entities": [(0, 21, "SYMPTOM"), (26, 35, "SYMPTOM")]}),
    ("Weakness and shortness of breath after climbing", {"entities": [(0, 8, "SYMPTOM"), (13, 32, "SYMPTOM")]}),
    ("Pale skin and dizziness occur daily", {"entities": [(0, 9, "SYMPTOM"), (14, 23, "SYMPTOM")]}),
    ("Blurred vision and nausea have worsened", {"entities": [(0, 14, "SYMPTOM"), (19, 25, "SYMPTOM")]}),
    ("Chest tightness and wheezing symptoms observed", {"entities": [(0, 15, "SYMPTOM"), (20, 28, "SYMPTOM")]}),
    ("Joint pain and fatigue getting worse", {"entities": [(0, 10, "SYMPTOM"), (15, 22, "SYMPTOM")]}),
    ("Loss of smell and dry cough for two days", {"entities": [(0, 14, "SYMPTOM"), (19, 28, "SYMPTOM")]}),
    ("Visual disturbance and dizziness together", {"entities": [(0, 18, "SYMPTOM"), (23, 32, "SYMPTOM")]}),
    ("Seizures and muscle stiffness seen again", {"entities": [(0, 8, "SYMPTOM"), (13, 29, "SYMPTOM")]}),
    ("Shortness of breath and pale skin", {"entities": [(0, 19, "SYMPTOM"), (24, 33, "SYMPTOM")]}),
    ("Frequent urination and blurred vision", {"entities": [(0, 19, "SYMPTOM"), (24, 38, "SYMPTOM")]}),
    ("Sweating and abdominal pain observed", {"entities": [(0, 8, "SYMPTOM"), (13, 27, "SYMPTOM")]}),
    ("Cough with phlegm and night sweats", {"entities": [(0, 17, "SYMPTOM"), (22, 34, "SYMPTOM")]}),
    ("Speech difficulty and numbness are present", {"entities": [(0, 17, "SYMPTOM"), (22, 30, "SYMPTOM")]}),
    ("Severe headache and sound sensitivity", {"entities": [(0, 15, "SYMPTOM"), (20, 37, "SYMPTOM")]}),
    ("Fatigue and nausea are ongoing", {"entities": [(0, 7, "SYMPTOM"), (12, 18, "SYMPTOM")]}),
]
